// Generated by https://quicktype.io

export interface IPokemonsResponse {
  data: IData;
  status: number;
  statusText: string;
  headers: IPokemonsResponseHeaders;
  config: IConfig;
  request: any;
}

export interface IConfig {
  url: string;
  method: string;
  headers: IConfigHeaders;
  transformRequest: null[];
  transformResponse: null[];
  timeout: number;
  xsrfCookieName: string;
  xsrfHeaderName: string;
  maxContentLength: number;
  maxBodyLength: number;
}

export interface IConfigHeaders {
  Accept: string;
}

export interface IData {
  count: number;
  next: string;
  previous: null;
  results: IPokemon[];
}

export interface IPokemon {
  name: string;
  url: string;
}

export interface IPokemonsResponseHeaders {
  "cache-control": string;
  "content-type": string;
}
